//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhyWeID.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_WhyWeId
    {
        public int ID { get; set; }
        public string PropertyId { get; set; }
        public string PropertyValue { get; set; }
        public byte Active { get; set; }
    }
}
