//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhyWeID.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WhyWeIDEntities : DbContext
    {
        public WhyWeIDEntities()
            : base("name=WhyWeIDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Reason> Reasons { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
        public virtual DbSet<sys_WhyWeId> sys_WhyWeId { get; set; }
    }
}
